//state argument is not applcation state, but only the state previous generated by the books reducer
export default function(state = null, action){
    switch (action.type){
        case 'BOOK_SELECTED':
            return action.payload;
    }
    return state;
}